apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: affinity-required
  name: affinity-required
spec:
  replicas: 10
  selector:
    matchLabels:
      run: affinity-required
  template:
    metadata:
      labels:
        run: affinity-required
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                run: affinity-required
      containers:
      - image: gashirar/k8s-debug-tools:v1
        name: affinity-required
        command: ["bash", "-c"]
        args:
        - echo "$K8S_POD_NAME -> $K8S_NODE_NAME";
          sleep infinity
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
