apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: anti-affinity-preferred
  name: anti-affinity-preferred
spec:
  replicas: 5
  selector:
    matchLabels:
      run: anti-affinity-preferred
  template:
    metadata:
      labels:
        run: anti-affinity-preferred
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: run
                  operator: In
                  values:
                  - anti-affinity-preferred
      containers:
      - image: gashirar/k8s-debug-tools:v1
        name: anti-affinity-preferred
        command: ["bash", "-c"]
        args:
        - echo "$K8S_POD_NAME -> $K8S_NODE_NAME";
          sleep infinity
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
