apiVersion: v1
kind: Pod
metadata:
  labels:
    run: downwardapi-example
  name: downwardapi-example
spec:
  containers:
  - image: centos
    name: downwardapi-example
    command: ["sleep", "864000"]
    volumeMounts:
    - mountPath: /log
      name: log-volume
    env:
      - name: K8S_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: K8S_HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: K8S_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: K8S_CONTAINER_NAME
        value: centos
      - name: K8S_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: K8S_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: K8S_POD_SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
  volumes:
  - name: log-volume
    hostPath:
      path: /var/log
      type: Directory

