commonLabels:
  app: sample

namePrefix:
  sample-

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- horizontalpodautoscaler.yaml
- serviceaccount.yaml
  #- poddisruptionbudget.yaml
  #- ingress.yaml
