commonLabels:
  app: petshop

namePrefix:
  petshop-

# nameSuffix:
#  -v1

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- horizontalpodautoscaler.yaml
- poddisruptionbudget.yaml
# - ingress.yaml
