apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    deployment: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: adapter-port
    name: service-port
