apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: adapter
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "200Mi"

