apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      serviceAccountName: hostpath-serviceaccount
      containers:
      - name: adapter
        securityContext:
          privileged: true
      - name: app
        securityContext:
          privileged: true

