apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "500Mi"

