bases:
- ../base

patches:
- deployment-adapter-cpu.yaml
- deployment-adapter-memory.yaml
- deployment-adapter-healthcheck.yaml
- deployment-app-cpu.yaml
- deployment-app-memory.yaml
- deployment-app-healthcheck.yaml
- deployment-replica.yaml
