apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    run: daemonset-example
  name: daemonset-example
spec:
  selector:
    matchLabels:
      name: daemonset-example
  updateStrategy:
    type : OnDelete
  template:
    metadata:
      labels:
        name: daemonset-example
    spec:
      containers:
      - image: gashirar/k8s-debug-tools:v1
        name: daemon
        command: ["bash", "-c"]
        args:
        - echo $K8S_NODE_NAME;
          sleep infinity;
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
