apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"run":"probe-example"},"name":"probe-example","namespace":"t-sawagashira"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"probe-example"}},"template":{"metadata":{"labels":{"run":"probe-example"}},"spec":{"containers":[{"image":"gashirar/k8s-debug-tools:v1","livenessProbe":{"exec":{"command":["true"]},"failureThreshold":1,"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"probe-example","ports":[{"containerPort":80,"name":"api-port"}],"readinessProbe":{"exec":{"command":["true"]},"failureThreshold":1,"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1}}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    run: probe-example
  name: probe-example
  selfLink: /apis/extensions/v1beta1/namespaces/t-sawagashira/deployments/probe-example
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: probe-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: probe-example
    spec:
      containers:
      - image: gashirar/k8s-debug-tools:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - "true"
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: probe-example
        ports:
        - containerPort: 80
          name: api-port
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - "true"
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
