apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: probe-example
  name: probe-example
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: probe-example
status:
  loadBalancer: {}
